import Head from 'next/head'; 
import { NextSeo } from 'next-seo';

export const CustomHead = ({title, description}) => {
    return (
      <>
          <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NextSeo
      title={title}
      description={description}
      canonical="https://www.canonical.ie/"
      openGraph={{
        url: 'https://www.url.ie/a',
        title: 'Open Graph Title',
        description: 'Open Graph Description',
        images: [
          {
            url: 'https://via.placeholder.com/1200x630.png',
            width: 1200,
            height: 600,
            alt: 'Og Image Alt test',
            type: 'image/jpeg',
          },
          {
            url: 'https://www.example.ie/og-image-02.jpg',
            width: 900,
            height: 800,
            alt: 'Og Image Alt Second test',
            type: 'image/jpeg',
          },
          { url: 'https://via.placeholder.com/1200x630.png' },
          { url: 'https://www.example.ie/og-image-04.jpg' },
        ],
        site_name: 'SiteName',
      }}
      twitter={{
        handle: '@handletest',
        site: '@sitetest',
        cardType: 'summary_large_image',
      }}
    />
      </>
    )
};